run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    local-prefixes: github.com/willams/lia

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
